services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
  
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - ./config.env
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    volumes:
      - /usr/src/app/node_modules

volumes:
  mongodb_data: